### ISSUE TITLE
AC protocol

### ISSUE THREAD

**Issue by flowtron** [elmillion/assaultcube_server_reader#1]
In https://github.com/elmillion/assaultcube_server_reader/commit/876737497e78952af2b6cbe79823bc62eef3e0f7 you mention a FIXME regarding variable byte length numbers – have you inspected the AssaultCube source? Specifically protocol.cpp: putint_(), putaint_() and putuint_().

**Comment by elmillion** [comment]
I will have a look at it, thank you !

Sorry for the delayed answer, I was away 😄

**Comment by elmillion** [comment]
Should be ok for the case `n<0x8000 && n>=-0x8000` !

Thank you !
